name: Pentaho release workflow
on:
  workflow_call:

jobs:

  pentaho-release:

    runs-on: [ k8s ]

    container:
      image: docker.repo.orl.eng.hitachivantara.com/pentaho/actions-common:20230712.10

    steps:

      - name: Promote artifacts
        run: echo "Do something"

      - name: Push artifacts to Box
        run: echo "Do something"
